import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// TODO: Add metadata, opengraph image, and favicon

export const metadata: Metadata = {
  title: "EgaErinovian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
